spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_db
    username: postgres
    password: 216C1A0502
    spring.driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties :
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect